### ISSUE TITLE
smesh fails to build with OCE 0.13

### ISSUE THREAD

**Issue by hobbes1069** [tpaviot/oce#409]
```
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp:164:29: error: 'OuterShell' is not a member of 'BRepTools'
   TopoDS_Shell outerShell = BRepTools::OuterShell( solid );
```

BRepTools::OuterShell is now obsolete and replaced by BRepClass3d::OuterShell
http://tracker.dev.opencascade.org/view.php?id=23487

Attempted a patch:

```
diff -Naur smesh-5.1.2.2.svn55.orig/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp
--- smesh-5.1.2.2.svn55.orig/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp       2009-12-16 09:01:21.000000000 -0600
+++ smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp    2013-09-22 21:30:43.995137618 -0500
@@ -46,6 +46,8 @@
 #include <BRepBuilderAPI_MakeEdge.hxx>
 #include <BRepTools.hxx>
 #include <BRep_Tool.hxx>
+#include <BRep_Builder.hxx>
+#include <BRepClass3d.hxx>
 #include <TopExp_Explorer.hxx>
 #include <TopoDS.hxx>
 #include <TopoDS_Shell.hxx>
@@ -161,7 +163,7 @@

   // get 2 shells
   TopoDS_Solid solid = TopoDS::Solid( aShape );
-  TopoDS_Shell outerShell = BRepTools::OuterShell( solid );
+  TopoDS_Shell outerShell = BRepClass3d::OuterShell( solid );
   TopoDS_Shape innerShell;
   int nbShells = 0;
   for ( TopoDS_Iterator It (solid); It.More(); It.Next(), ++nbShells )
@@ -401,7 +403,7 @@
 {
   // get 2 shells
   TopoDS_Solid solid = TopoDS::Solid( aShape );
-  TopoDS_Shell outerShell = BRepTools::OuterShell( solid );
+  TopoDS_Shell outerShell = BRepClass3d::OuterShell( solid );
   TopoDS_Shape innerShell;
   int nbShells = 0;
   for ( TopoDS_Iterator It (solid); It.More(); It.Next(), ++nbShells )
```

But I still get an error:

```
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp: In member function 'virtual bool StdMeshers_RadialPrism_3D::Evaluate(SMESH_Mesh&, const TopoDS_Shape&, MapShapeNbElems&)':
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp:406:27: error: expected initializer before 'BRepClass3d'
   TopoDS_Shell outerShell BRepClass3d::OuterShell( solid );
                           ^
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp:410:11: error: 'outerShell' was not declared in this scope
     if ( !outerShell.IsSame( It.Value() ))
           ^
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp:424:46: error: 'outerShell' was not declared in this scope
   if ( !TAssocTool::FindSubShapeAssociation( outerShell, &aMesh,
                                              ^
/builddir/build/BUILD/smesh-5.1.2.2.svn55/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp:439:28: error: 'outerShell' was not declared in this scope
   for (TopExp_Explorer exp(outerShell, TopAbs_FACE); exp.More(); exp.Next()) {
                            ^

```
